### ISSUE TITLE
Consider adding API reference?

### ISSUE THREAD

**Issue by athulpg007** [jbussemaker/SBArchOpt#5]
Would it help users to have an API reference for SBArchOpt such as these?
1. https://pymoo.org/api/algorithms.html
2. https://secondmind-labs.github.io/trieste/1.1.2/autoapi/trieste/bayesian_optimizer/index.html

**Comment by jbussemaker** [comment]
@athulpg007 thank you for the suggestion, I have upgraded the docs to a static website (including API reference): https://sbarchopt.readthedocs.io/

**Comment by athulpg007** [comment]
Thanks for adding the docs and the API reference.
